Repository TeamGromit/Gromit-client-iOS, pull requests merged in 2023-01, with the labels that each got.

#6 feat: 애플 로그인 화면 수정 및 깃 유저 검색 화면 생성
  Gromit-client-iOS.xcodeproj/project.pbxproj
  Gromit-client-iOS/Gromit-client-iOS.entitlements
  Gromit-client-iOS/Source/Models/SearchGitUser.swift
  Gromit-client-iOS/Source/Views/SearchGitUserView.swift
  Gromit-client-iOS/Source/Views/SignInView.swift
  Gromit-client-iOS/Source/Views/TempView.swift
Labels: feat

#11 feat: ui 이미지 추가, SignInView 및 TempView 수정, SearchGitUserView 구현
  Gromit-client-iOS/Resources/Assets.xcassets/delete_ui.imageset/Contents.json
  Gromit-client-iOS/Resources/Assets.xcassets/delete_ui.imageset/delete_ui 1.png
  Gromit-client-iOS/Resources/Assets.xcassets/delete_ui.imageset/delete_ui 2.png
  Gromit-client-iOS/Resources/Assets.xcassets/delete_ui.imageset/delete_ui.png
  Gromit-client-iOS/Source/Views/SearchGitUserView.swift
  Gromit-client-iOS/Source/Views/SignInView.swift
  Gromit-client-iOS/Source/Views/TempView.swift
Labels: feat

#15 test: SignInView, SearchGitUserView 수정 및 테스트용
  Gromit-client-iOS.xcodeproj/project.pbxproj
  Gromit-client-iOS/Source/Views/SearchGitUserView.swift
  Gromit-client-iOS/Source/Views/SignInView.swift
Labels: help wanted

#18 add: Moya 라이브러리 추가
  Gromit-client-iOS.xcodeproj/project.pbxproj
Labels: feat

#19 add: .gitattributes, .gitignore 추가
  .gitattributes
  .gitignore
Labels: documentation

#24 feat: getGitUserName 통신 구현
  Gromit-client-iOS.xcodeproj/project.pbxproj
  Gromit-client-iOS/Constants.swift
  Gromit-client-iOS/Models/User.swift
  Gromit-client-iOS/Services/Entities/SearchGitUserEntity.swift
  Gromit-client-iOS/Services/GeneralAPI.swift
  Gromit-client-iOS/Services/LoginServices.swift
  Gromit-client-iOS/Views/CollectionListView.swift
  Gromit-client-iOS/Views/FinalLevelView.swift
  Gromit-client-iOS/Views/HomeView.swift
  Gromit-client-iOS/Views/SearchGitUserView.swift
  Gromit-client-iOS/Views/SearchGitUserViewModel.swift
  Gromit-client-iOS/Views/TempSearchGitUserView.swift
  Gromit-client-iOS/Views/TempView.swift
Labels: feat

#25 modify: 코드 수정
  Gromit-client-iOS/Services/Entities/LoginWithAppleEntity.swift
  Gromit-client-iOS/Views/SignInView.swift
Labels: style
